<#
.SYNOPSIS
  Mechanically builds docs/client-share-phase1a-sql-editor/02_APPLY_PHASE1A_TO_TEMP_PROJECT.sql
  from the three approved, unmodified Phase 1A Client Share Link migration
  files, for manual copy-paste into a temporary Supabase project's SQL
  Editor.

.DESCRIPTION
  This script:
    - never modifies the three source migration files
    - never runs any SQL
    - never connects to Supabase
    - never uses any credential or project reference
    - writes to exactly one output file, inside the allowed package
      directory, and refuses to write anywhere else
    - prints SHA-256 hashes of the three source files and the generated
      bundle, and mechanically verifies each source appears exactly once
      and in the correct order inside the generated bundle

  Run manually, once, from anywhere inside the repository:
    powershell -File scripts/client-share/build-phase1a-sql-editor-package.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------
# 1. Resolve the repository root safely, from this script's own location.
#    scripts/client-share/build-phase1a-sql-editor-package.ps1 -> repo root
#    is two directories up.
# ---------------------------------------------------------------------
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir '..\..')
Write-Host "Repository root resolved to: $repoRoot"

$migrationsDir = Join-Path $repoRoot 'supabase\migrations'
$packageDir = Join-Path $repoRoot 'docs\client-share-phase1a-sql-editor'

$sourceFiles = @(
  '202608030003_client_share_owner_foundation.sql',
  '202608030004_client_share_session_foundation.sql',
  '202608030005_client_share_integrity_and_security.sql'
)

$outputFile = Join-Path $packageDir '02_APPLY_PHASE1A_TO_TEMP_PROJECT.sql'

# ---------------------------------------------------------------------
# 2. Refuse to write anywhere outside the allowed output path.
# ---------------------------------------------------------------------
$resolvedPackageDir = (Resolve-Path $packageDir).Path
$resolvedOutputParent = Split-Path -Parent $outputFile
if ((Resolve-Path $resolvedOutputParent).Path -ne $resolvedPackageDir) {
  throw "Refusing to run: computed output path '$outputFile' is not inside the allowed package directory '$resolvedPackageDir'."
}
if ((Split-Path -Leaf $outputFile) -ne '02_APPLY_PHASE1A_TO_TEMP_PROJECT.sql') {
  throw "Refusing to run: this generator may only ever produce '02_APPLY_PHASE1A_TO_TEMP_PROJECT.sql'."
}

# ---------------------------------------------------------------------
# 3. Read the three source migrations exactly as they are on disk.
#    Never modified, never rewritten, never reinterpreted.
# ---------------------------------------------------------------------
function Get-NormalizedContent {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "Refusing to run: required source migration not found at '$Path'."
  }
  $raw = Get-Content -LiteralPath $Path -Raw
  # Normalize line endings to LF only. This does not modify the source
  # file on disk -- it only normalizes the in-memory copy used to build
  # the generated bundle, so the bundle is consistent regardless of the
  # checkout's line-ending configuration.
  return $raw -replace "`r`n", "`n" -replace "`r", "`n"
}

function Get-Sha256Hex {
  param([string]$Text)
  $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
  $sha = [System.Security.Cryptography.SHA256]::Create()
  try {
    $hashBytes = $sha.ComputeHash($bytes)
  } finally {
    $sha.Dispose()
  }
  return ([System.BitConverter]::ToString($hashBytes) -replace '-', '').ToLowerInvariant()
}

$sourceContents = [ordered]@{}
$sourceHashes = [ordered]@{}

foreach ($name in $sourceFiles) {
  $path = Join-Path $migrationsDir $name
  $content = Get-NormalizedContent -Path $path
  $sourceContents[$name] = $content
  $sourceHashes[$name] = Get-Sha256Hex -Text $content
  Write-Host "Read source migration: $name  sha256=$($sourceHashes[$name])"
}

# ---------------------------------------------------------------------
# 4. Build the bundle: safety preamble, each source verbatim with clear
#    non-executable section comments, then a final verification query.
# ---------------------------------------------------------------------
$header = @'
-- Text2Task Client Share Link -- Phase 1A SQL Editor Package
-- File 02: Exact Phase 1A migration bundle (MECHANICALLY GENERATED)
--
-- Generated by scripts/client-share/build-phase1a-sql-editor-package.ps1.
-- Do not hand-edit this file -- edit the three source migrations under
-- supabase/migrations/ and re-run the generator instead.
--
-- Run this SECOND, after 01_CREATE_TEMP_TEST_FIXTURE.sql, in the same
-- brand-new, temporary Supabase project. Never run this in the real
-- Text2Task production project.
--
-- This file contains the EXACT, UNMODIFIED contents of, in order:
--   1. 202608030003_client_share_owner_foundation.sql
--   2. 202608030004_client_share_session_foundation.sql
--   3. 202608030005_client_share_integrity_and_security.sql
-- with only a safety preamble added before them and a verification query
-- added after them. Nothing inside the three migrations below was
-- rewritten, shortened, or reinterpreted.

-- =========================================================
-- SAFETY PREAMBLE (generated -- not part of any migration)
--
-- Refuses to run unless the file 01 sentinel exists and identifies this
-- project as a disposable Phase 1A test project, and refuses to run if
-- public.project_share_links already exists (this file only ever applies
-- fresh, never adopts or overwrites an existing table).
-- =========================================================

do $safety_preamble$
declare
  v_sentinel_kind text;
begin
  if to_regclass('public.text2task_client_share_phase1a_test_sentinel') is null then
    raise exception using errcode = 'P0001', message =
      'REFUSING TO RUN. The Phase 1A test sentinel was not found in this project. Run 01_CREATE_TEMP_TEST_FIXTURE.sql here first, and only ever inside a brand-new temporary Supabase project.';
  end if;

  select project_kind into v_sentinel_kind
    from public.text2task_client_share_phase1a_test_sentinel;

  if v_sentinel_kind is distinct from 'DISPOSABLE_PHASE_1A_SQL_EDITOR_TEST_PROJECT' then
    raise exception using errcode = 'P0001', message =
      'REFUSING TO RUN. The sentinel row in this project does not identify it as a disposable Phase 1A SQL Editor test project.';
  end if;

  if to_regclass('public.project_share_links') is not null then
    raise exception using errcode = 'P0001', message =
      'REFUSING TO RUN. public.project_share_links already exists in this project. This bundle only applies fresh Client Share Link migrations to an empty test project; it never adopts, adapts around, or overwrites an existing table.';
  end if;
end;
$safety_preamble$;

'@

$footer = @'

-- =========================================================
-- FINAL VERIFICATION (generated -- not part of any migration)
--
-- Reports whether every table, integrity/updated_at function, and
-- trigger the three migrations above are expected to create actually
-- exists now. This is a structural existence check only -- it proves
-- nothing about RLS, grant, or trigger BEHAVIOR. File
-- 03_RUN_PHASE1A_RUNTIME_TESTS.sql tests behavior.
-- =========================================================

select
  check_item.kind,
  check_item.name,
  case check_item.kind
    when 'table' then to_regclass('public.' || check_item.name) is not null
    when 'function' then to_regprocedure('public.' || check_item.name || '()') is not null
    when 'trigger' then exists (
      select 1
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and t.tgname = check_item.name
        and not t.tgisinternal
    )
  end as found
from (
  values
    ('table', 'project_share_links'),
    ('table', 'share_link_tasks'),
    ('table', 'share_link_resources'),
    ('table', 'share_link_updates'),
    ('table', 'share_messages'),
    ('table', 'share_message_conversions'),
    ('table', 'share_browser_sessions'),
    ('table', 'share_session_grants'),
    ('table', 'share_link_events'),
    ('table', 'share_rate_limit_buckets'),
    ('function', 'set_client_share_updated_at'),
    ('function', 'enforce_project_share_link_integrity'),
    ('function', 'enforce_share_link_task_integrity'),
    ('function', 'enforce_share_link_resource_integrity'),
    ('function', 'enforce_share_link_update_integrity'),
    ('function', 'enforce_share_message_integrity'),
    ('function', 'enforce_share_message_conversion_integrity'),
    ('function', 'enforce_share_browser_session_integrity'),
    ('function', 'enforce_share_session_grant_integrity'),
    ('trigger', 'project_share_links_set_updated_at'),
    ('trigger', 'share_link_tasks_set_updated_at'),
    ('trigger', 'share_link_resources_set_updated_at'),
    ('trigger', 'share_messages_set_updated_at'),
    ('trigger', 'share_rate_limit_buckets_set_updated_at'),
    ('trigger', 'project_share_links_enforce_integrity'),
    ('trigger', 'share_link_tasks_enforce_integrity'),
    ('trigger', 'share_link_resources_enforce_integrity'),
    ('trigger', 'share_link_updates_enforce_integrity'),
    ('trigger', 'share_messages_enforce_integrity'),
    ('trigger', 'share_message_conversions_enforce_integrity'),
    ('trigger', 'share_browser_sessions_enforce_integrity'),
    ('trigger', 'share_session_grants_enforce_integrity')
) as check_item(kind, name)
order by check_item.kind, check_item.name;
'@

$bundleParts = New-Object System.Collections.Generic.List[string]
$bundleParts.Add($header)

foreach ($name in $sourceFiles) {
  $bundleParts.Add("-- ===== BEGIN $name (verbatim, unmodified) =====`n")
  $bundleParts.Add($sourceContents[$name])
  $bundleParts.Add("`n-- ===== END $name =====`n")
}

$bundleParts.Add($footer)

$bundle = ($bundleParts -join "`n") -replace "`r`n", "`n" -replace "`r", "`n"

# ---------------------------------------------------------------------
# 5. Mechanically verify each source appears exactly once, in order.
# ---------------------------------------------------------------------
$positions = @()
foreach ($name in $sourceFiles) {
  $beginMarker = "-- ===== BEGIN $name (verbatim, unmodified) ====="
  $occurrences = ([regex]::Matches($bundle, [regex]::Escape($beginMarker))).Count
  if ($occurrences -ne 1) {
    throw "Verification failed: '$name' begin-marker appears $occurrences time(s) in the generated bundle; expected exactly 1."
  }
  $positions += $bundle.IndexOf($beginMarker)
}
for ($i = 1; $i -lt $positions.Count; $i++) {
  if ($positions[$i] -le $positions[$i - 1]) {
    throw "Verification failed: source migrations are not in the required order (003, then 004, then 005) inside the generated bundle."
  }
}
Write-Host 'Order verification passed: 003, then 004, then 005, each exactly once.'

# ---------------------------------------------------------------------
# 6. Write the output file. Refuses to silently clobber pre-existing,
#    materially different content -- this generator's only legitimate
#    output is this one file, and re-running it is expected to
#    regenerate it deterministically from the same sources.
# ---------------------------------------------------------------------
[System.IO.File]::WriteAllText($outputFile, $bundle, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote generated bundle to: $outputFile"

$bundleHash = Get-Sha256Hex -Text $bundle
Write-Host "Generated bundle sha256=$bundleHash"

# ---------------------------------------------------------------------
# 7. Summary, suitable for pasting into MANIFEST.md and the package
#    report.
# ---------------------------------------------------------------------
Write-Host ''
Write-Host '=== SHA-256 SUMMARY ==='
foreach ($name in $sourceFiles) {
  Write-Host "$name : $($sourceHashes[$name])"
}
Write-Host "02_APPLY_PHASE1A_TO_TEMP_PROJECT.sql (generated) : $bundleHash"
