-- Text2Task Client Share Link -- Phase 6C Atomic Apply + Conversion Closure
-- Migration: 202608230002_client_share_apply_conversion_closure.sql
-- Created: 2026-08-23
--
-- Mechanically generated by
-- scripts/client-share/build-phase6c-apply-conversion-closure-migration.ps1.
-- Do not hand-edit this file -- edit the relevant source migration and
-- re-run the generator instead. See that script's own header comment and
-- docs/TEXT2TASK_CLIENT_SHARE_LINK_PHASE_6C_AUDIT_AND_PLAN_2026-08-23.md
-- for the full design, including a final pre-implementation security
-- audit (verdict at the time: PHASE_6C_PLAN_SECURITY_BLOCKED) and the
-- row-bound transaction-capability correction that resolved it.
--
-- SECURITY DESIGN (see the plan document sections 6-9 for full detail):
-- project_updates carries a broad, column-unrestricted `authenticated`
-- RLS UPDATE policy, with no trigger guarding `status` beyond the
-- existing Phase 6B boundary. A prior draft of this migration would have
-- fully DROPped that boundary once this closure existed -- a security
-- audit found this unsafe: an owner could raw-UPDATE their own
-- client_share row directly to status='applied' (zero real work), then
-- call a standalone conversion helper directly, and every one of that
-- helper's originally-proposed checks would have passed. This migration
-- does NOT drop the Phase 6B boundary trigger or its function -- it
-- narrows the function's predicate in place (CREATE OR REPLACE only) and
-- introduces a transaction-local, ROW-BOUND capability
-- (text2task.client_share_apply_update_id, set via set_config with
-- is_local=true -- never a boolean/global flag) that only
-- apply_project_update_transaction itself can ever set, immediately
-- before its own authoritative applied-status transition.
-- finalize_share_message_conversion independently requires the SAME
-- capability, bound to the exact project_update id, before any of its
-- other (still independently necessary) checks -- closing the
-- standalone-invocation path even if project_updates.status='applied' is
-- ever forged by other means, without broadening any grant and without
-- changing text/image Apply behavior at all.
--
-- This migration, in order:
--   1. CREATE public.finalize_share_message_conversion (new, SECURITY
--      DEFINER) -- the conversion-closure helper.
--   2. CREATE OR REPLACE public.apply_project_update_transaction, adding
--      the row-bound capability (immediately before the existing
--      applied-status UPDATE) and the closure-block call (immediately
--      before the existing final return) -- same six-argument signature,
--      same SECURITY INVOKER, same grants; every other line preserved
--      verbatim from 202607270001.
--   3. CREATE OR REPLACE public.set_share_message_status, adding the
--      SHARE_MESSAGE_STATUS_TERMINAL guard before any status mutation --
--      same signature, same SECURITY DEFINER, same grants; every other
--      line preserved verbatim from 202608190001.
--   4. CREATE OR REPLACE public.enforce_project_update_client_share_apply_boundary
--      (the Phase 6B trigger FUNCTION only -- the trigger itself,
--      project_updates_enforce_client_share_apply_boundary, is NEVER
--      dropped and does not need to be, and is not, redeclared): 'applying'
--      is no longer blocked (the real Apply RPC always independently
--      re-validates and performs real work regardless of how 'applying'
--      was reached); an *entering* transition into 'applied' (a direct
--      INSERT already at 'applied', or an UPDATE from any non-'applied'
--      prior status) is permitted only when the transaction-local
--      capability matches the exact row id; an already-applied row
--      receiving an ordinary non-status update does not require the
--      capability.
--
-- No transient unsafe ordering: if this migration is interrupted after
-- step 3 but before step 4, the system remains SAFE -- client_share is
-- still blocked from applying/applied by the still-present, still-
-- unmodified Phase 6B trigger body, while the new closure logic sits
-- ready but inert (any attempt by the RPC to reach 'applied' would be
-- rejected by the still-old trigger body, aborting the whole Apply
-- transaction cleanly -- a hard failure, not a silent gap).
--
-- No historical migration is edited -- 202607270001, 202608190001,
-- 202608210001, and 202608230001 all remain exactly as they are; this is
-- a wholly new file. No new table, no new column.

-- =========================================================
-- 1. public.finalize_share_message_conversion (new)
-- =========================================================

create or replace function public.finalize_share_message_conversion(
  p_message_id uuid,
  p_project_update_id uuid
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_update_status text;
  v_update_source_type text;
  v_update_source_share_message_id uuid;
  v_update_project_id uuid;
  v_message_user_id uuid;
  v_message_project_id uuid;
  v_message_author_type text;
  v_message_status text;
  v_converted_at timestamptz := now();
  v_affected_count integer := 0;
begin
  if v_user_id is null then
    raise exception using errcode = 'P0001', message = 'UNAUTHORIZED';
  end if;

  -- Phase 6C security correction: this transaction-local, row-bound
  -- capability is the FIRST check, before any other validation. It can
  -- only be 'on' for this exact p_project_update_id inside the one
  -- transaction where apply_project_update_transaction itself set it,
  -- immediately before performing the real, authoritative applied
  -- transition for that row. A standalone call to this function, in its
  -- own separate transaction, never has this capability set -- closing
  -- the forged-applied standalone-invocation attack the Phase 6C security
  -- audit found, independent of whatever project_updates.status reads as.
  if current_setting('text2task.client_share_apply_update_id', true)
      is distinct from p_project_update_id::text then
    raise exception using
      errcode = 'P0001',
      message = 'SHARE_CONVERSION_APPLY_CONTEXT_REQUIRED';
  end if;

  select
    update_row.status,
    update_row.source_type,
    update_row.source_share_message_id,
    update_row.project_id
    into
      v_update_status,
      v_update_source_type,
      v_update_source_share_message_id,
      v_update_project_id
    from public.project_updates as update_row
    where update_row.id = p_project_update_id
      and update_row.user_id = v_user_id
    for update;

  if v_update_status is null then
    raise exception using errcode = 'P0001', message = 'SHARE_CONVERSION_UPDATE_NOT_FOUND';
  end if;

  if v_update_status <> 'applied' then
    raise exception using errcode = 'P0001', message = 'SHARE_CONVERSION_UPDATE_NOT_APPLIED';
  end if;

  if v_update_source_type <> 'client_share' then
    raise exception using errcode = 'P0001', message = 'SHARE_CONVERSION_UPDATE_NOT_CLIENT_SHARE';
  end if;

  if v_update_source_share_message_id is distinct from p_message_id then
    raise exception using errcode = 'P0001', message = 'SHARE_CONVERSION_MESSAGE_MISMATCH';
  end if;

  select
    message.user_id,
    message.project_id,
    message.author_type,
    message.status
    into
      v_message_user_id,
      v_message_project_id,
      v_message_author_type,
      v_message_status
    from public.share_messages as message
    where message.id = p_message_id
      and message.user_id = v_user_id
    for update;

  if v_message_user_id is null then
    raise exception using errcode = 'P0001', message = 'SHARE_CONVERSION_MESSAGE_NOT_FOUND';
  end if;

  if v_message_project_id is distinct from v_update_project_id then
    raise exception using errcode = 'P0001', message = 'SHARE_CONVERSION_UPDATE_PROJECT_MISMATCH';
  end if;

  if v_message_author_type <> 'client' then
    raise exception using errcode = 'P0001', message = 'SHARE_CONVERSION_MESSAGE_NOT_CLIENT_AUTHORED';
  end if;

  if v_message_status = 'converted' then
    raise exception using errcode = 'P0001', message = 'SHARE_MESSAGE_STATUS_TERMINAL';
  end if;

  insert into public.share_message_conversions (
    user_id,
    message_id,
    project_update_id,
    target_task_id,
    converted_by,
    converted_at
  ) values (
    v_user_id,
    p_message_id,
    p_project_update_id,
    null,
    v_user_id,
    v_converted_at
  );

  update public.share_messages
    set
      status = 'converted',
      reviewed_at = coalesce(reviewed_at, v_converted_at)
    where id = p_message_id
      and user_id = v_user_id;

  get diagnostics v_affected_count = row_count;

  if v_affected_count <> 1 then
    raise exception using errcode = 'P0001', message = 'SHARE_CONVERSION_MESSAGE_UPDATE_FAILED';
  end if;
end;
$$;


comment on function public.finalize_share_message_conversion(uuid, uuid) is
  'Phase 6C: atomic conversion-closure helper for client_share Apply. SECURITY DEFINER, callable directly by authenticated (required for the still-SECURITY INVOKER apply_project_update_transaction''s own perform call to succeed) -- therefore a complete, independent authorization boundary. Requires the transaction-local capability text2task.client_share_apply_update_id, bound to the exact p_project_update_id, before any other check or write -- a standalone call in its own transaction never has this set. Also independently re-validates ownership, applied status, client_share provenance, message linkage, author type, and not-already-converted -- a second, independent layer, not a replacement for the capability check. Writes exactly one share_message_conversions row and updates share_messages.status=''converted''; never touches resolved_at; target_task_id is always null in Phase 6C.';

revoke all on function public.finalize_share_message_conversion(uuid, uuid) from public;
revoke all on function public.finalize_share_message_conversion(uuid, uuid) from anon;
revoke all on function public.finalize_share_message_conversion(uuid, uuid) from service_role;
grant execute on function public.finalize_share_message_conversion(uuid, uuid) to authenticated;

-- =========================================================
-- 2. public.apply_project_update_transaction (CREATE OR REPLACE --
--    same signature/security/grants, preserved from 202607270001 except
--    for the two Phase 6C insertions proven above)
-- =========================================================

create or replace function public.apply_project_update_transaction(
  p_update_id uuid,
  p_apply_attempt_id uuid,
  p_accepted_item_ids uuid[],
  p_rejected_item_ids uuid[],
  p_edited_items jsonb,
  p_apply_payload jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_update public.project_updates%rowtype;
  v_final_update public.project_updates%rowtype;
  v_project public.projects%rowtype;
  v_client public.clients%rowtype;
  v_item public.project_update_items%rowtype;
  v_event public.project_timeline_events%rowtype;
  v_payload_item jsonb;
  v_edited_item jsonb;
  v_mutation jsonb;
  v_updates jsonb;
  v_project_client_updates jsonb;
  v_client_updates jsonb;
  v_task_client_updates jsonb;
  v_event_payload jsonb;
  v_task_payload jsonb;
  v_accepted_ids uuid[];
  v_rejected_ids uuid[];
  v_all_ids uuid[];
  v_item_id uuid;
  v_task_id bigint;
  v_next_subtask_order integer;
  v_expected_count integer := 0;
  v_affected_count integer := 0;
  v_created_timeline_events jsonb := '[]'::jsonb;
  v_applied_items jsonb := '[]'::jsonb;
  v_rejected_items jsonb := '[]'::jsonb;
  v_has_priority_change boolean := false;
  v_event_new_value jsonb;
begin
  if v_user_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'UNAUTHORIZED';
  end if;

  if p_update_id is null or p_apply_attempt_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'INVALID_APPLY_ATTEMPT';
  end if;

  if p_edited_items is null or jsonb_typeof(p_edited_items) <> 'array'
    or p_apply_payload is null or jsonb_typeof(p_apply_payload) <> 'array' then
    raise exception using
      errcode = 'P0001',
      message = 'INVALID_APPLY_PAYLOAD';
  end if;

  select coalesce(
    array_agg(distinct requested.item_id order by requested.item_id),
    array[]::uuid[]
  )
  into v_accepted_ids
  from unnest(coalesce(p_accepted_item_ids, array[]::uuid[]))
    as requested(item_id)
  where requested.item_id is not null;

  select coalesce(
    array_agg(distinct requested.item_id order by requested.item_id),
    array[]::uuid[]
  )
  into v_rejected_ids
  from unnest(coalesce(p_rejected_item_ids, array[]::uuid[]))
    as requested(item_id)
  where requested.item_id is not null;

  if cardinality(v_accepted_ids) + cardinality(v_rejected_ids) = 0 then
    raise exception using
      errcode = 'P0001',
      message = 'INVALID_ITEM_SELECTION';
  end if;

  if cardinality(v_accepted_ids) + cardinality(v_rejected_ids) > 500 then
    raise exception using
      errcode = 'P0001',
      message = 'TOO_MANY_UPDATE_ITEMS';
  end if;

  if exists (
    select 1
    from unnest(v_accepted_ids) as accepted(item_id)
    where accepted.item_id = any(v_rejected_ids)
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'ITEM_SELECTION_CONFLICT';
  end if;

  select array_agg(selected.item_id order by selected.item_id)
  into v_all_ids
  from (
    select unnest(v_accepted_ids) as item_id
    union all
    select unnest(v_rejected_ids) as item_id
  ) as selected;

  select update_row.*
  into v_update
  from public.project_updates as update_row
  where update_row.id = p_update_id
    and update_row.user_id = v_user_id
  for update of update_row;

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'PROJECT_UPDATE_NOT_FOUND';
  end if;

  if v_update.status <> 'applying'
    or v_update.apply_attempt_id is distinct from p_apply_attempt_id then
    raise exception using
      errcode = 'P0001',
      message = 'APPLY_ATTEMPT_MISMATCH';
  end if;

  select project.*
  into v_project
  from public.projects as project
  where project.id = v_update.project_id
    and project.user_id = v_user_id
    and project.deleted_at is null
  for update of project;

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'PROJECT_NOT_FOUND';
  end if;

  if v_project.client_id is not null then
    select client.*
    into v_client
    from public.clients as client
    where client.id = v_project.client_id
      and client.user_id = v_user_id
    for update of client;

    if not found then
      raise exception using
        errcode = 'P0001',
        message = 'CLIENT_NOT_FOUND';
    end if;
  end if;

  -- Stabilize task targets and subtask ordering before any mutation.
  for v_task_id in
    select task.id
    from public.tasks as task
    where task.project_id = v_project.id
      and task.user_id = v_user_id
      and task.deleted_at is null
    order by task.id
    for update of task
  loop
    null;
  end loop;

  v_expected_count := 0;

  for v_item_id in
    select item.id
    from public.project_update_items as item
    where item.id = any(v_all_ids)
      and item.project_update_id = v_update.id
      and item.project_id = v_project.id
      and item.user_id = v_user_id
      and item.status in ('suggested', 'accepted', 'rejected')
    order by item.id
    for update of item
  loop
    v_expected_count := v_expected_count + 1;
  end loop;

  if v_expected_count <> cardinality(v_all_ids) then
    raise exception using
      errcode = 'P0001',
      message = 'ITEM_VALIDATION_FAILED';
  end if;

  if jsonb_array_length(p_apply_payload) <> cardinality(v_accepted_ids) then
    raise exception using
      errcode = 'P0001',
      message = 'APPLY_PAYLOAD_ITEM_MISMATCH';
  end if;

  select count(distinct (payload.value->>'itemId')::uuid)::integer
  into v_expected_count
  from jsonb_array_elements(p_apply_payload) as payload(value)
  where jsonb_typeof(payload.value) = 'object'
    and payload.value ? 'itemId'
    and (payload.value->>'itemId')::uuid = any(v_accepted_ids);

  if v_expected_count <> cardinality(v_accepted_ids) then
    raise exception using
      errcode = 'P0001',
      message = 'APPLY_PAYLOAD_ITEM_MISMATCH';
  end if;

  if jsonb_array_length(p_edited_items) > cardinality(v_accepted_ids) then
    raise exception using
      errcode = 'P0001',
      message = 'INVALID_EDITED_ITEMS';
  end if;

  if exists (
    select 1
    from public.project_timeline_events as event
    where event.source_update_id = v_update.id
      and event.source_item_id = any(v_accepted_ids)
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'TIMELINE_EVENT_ALREADY_EXISTS';
  end if;

  for v_edited_item in
    select edited.value
    from jsonb_array_elements(p_edited_items) as edited(value)
  loop
    if jsonb_typeof(v_edited_item) <> 'object'
      or not (v_edited_item ? 'itemId')
      or not (v_edited_item ? 'newValue')
      or jsonb_typeof(v_edited_item->'newValue') <> 'object' then
      raise exception using
        errcode = 'P0001',
        message = 'INVALID_EDITED_ITEMS';
    end if;

    v_item_id := (v_edited_item->>'itemId')::uuid;

    if not (v_item_id = any(v_accepted_ids)) then
      raise exception using
        errcode = 'P0001',
        message = 'INVALID_EDITED_ITEMS';
    end if;

    update public.project_update_items as item
    set new_value = v_edited_item->'newValue'
    where item.id = v_item_id
      and item.project_update_id = v_update.id
      and item.project_id = v_project.id
      and item.user_id = v_user_id
      and item.status in ('suggested', 'accepted', 'rejected');

    get diagnostics v_affected_count = row_count;

    if v_affected_count <> 1 then
      raise exception using
        errcode = 'P0001',
        message = 'EDITED_ITEM_UPDATE_FAILED';
    end if;
  end loop;

  for v_payload_item in
    select payload.value
    from jsonb_array_elements(p_apply_payload) with ordinality
      as payload(value, item_order)
    order by payload.item_order
  loop
    if jsonb_typeof(v_payload_item) <> 'object'
      or not (v_payload_item ? 'itemId')
      or not (v_payload_item ? 'itemType')
      or jsonb_typeof(v_payload_item->'mutation') <> 'object'
      or jsonb_typeof(v_payload_item->'event') <> 'object' then
      raise exception using
        errcode = 'P0001',
        message = 'INVALID_APPLY_PAYLOAD';
    end if;

    v_item_id := (v_payload_item->>'itemId')::uuid;

    select item.*
    into v_item
    from public.project_update_items as item
    where item.id = v_item_id
      and item.project_update_id = v_update.id
      and item.project_id = v_project.id
      and item.user_id = v_user_id
      and item.status in ('suggested', 'accepted', 'rejected')
    for update of item;

    if not found
      or not (v_item.id = any(v_accepted_ids))
      or v_item.type is distinct from v_payload_item->>'itemType'
      or coalesce(v_item.new_value, 'null'::jsonb)
        is distinct from coalesce(v_payload_item->'newValue', 'null'::jsonb) then
      raise exception using
        errcode = 'P0001',
        message = 'APPLY_PAYLOAD_ITEM_MISMATCH';
    end if;

    if v_item.target_task_id is not null
      and not exists (
        select 1
        from public.tasks as task
        where task.id = v_item.target_task_id
          and task.project_id = v_project.id
          and task.user_id = v_user_id
          and task.deleted_at is null
      ) then
      raise exception using
        errcode = 'P0001',
        message = 'TARGET_TASK_VALIDATION_FAILED';
    end if;

    v_mutation := v_payload_item->'mutation';
    v_event_payload := v_payload_item->'event';
    v_task_id := null;
    v_event_new_value := v_item.new_value;
    v_project_client_updates := '{}'::jsonb;
    v_client_updates := '{}'::jsonb;
    v_task_client_updates := '{}'::jsonb;

    if v_item.type = 'new_subtask' then
      if v_mutation->>'kind' is distinct from 'new_subtask'
        or jsonb_typeof(v_mutation->'task') <> 'object' then
        raise exception using
          errcode = 'P0001',
          message = 'INVALID_NEW_SUBTASK_PAYLOAD';
      end if;

      v_task_payload := v_mutation->'task';

      if nullif(btrim(v_task_payload->>'task_title'), '') is null
        or (
          v_task_payload - array[
            'client_name',
            'contact_name',
            'task_title',
            'amount',
            'amount_value',
            'currency_code',
            'deadline_text',
            'deadline_date',
            'priority',
            'status'
          ]
        ) <> '{}'::jsonb then
        raise exception using
          errcode = 'P0001',
          message = 'INVALID_NEW_SUBTASK_PAYLOAD';
      end if;

      select coalesce(max(task.subtask_order), 0) + 1
      into v_next_subtask_order
      from public.tasks as task
      where task.project_id = v_project.id
        and task.user_id = v_user_id
        and task.deleted_at is null;

      insert into public.tasks (
        user_id,
        client_name,
        contact_name,
        client_id,
        project_id,
        subtask_order,
        task_title,
        amount,
        amount_value,
        currency_code,
        deadline_text,
        deadline_date,
        priority,
        status,
        source,
        raw_input,
        is_archived,
        archived_at,
        completed_at,
        deleted_at,
        updated_at
      )
      values (
        v_user_id,
        v_task_payload->>'client_name',
        nullif(v_task_payload->>'contact_name', ''),
        v_project.client_id,
        v_project.id,
        v_next_subtask_order,
        v_task_payload->>'task_title',
        nullif(v_task_payload->>'amount', ''),
        nullif(v_task_payload->>'amount_value', '')::numeric,
        nullif(v_task_payload->>'currency_code', ''),
        nullif(v_task_payload->>'deadline_text', ''),
        nullif(v_task_payload->>'deadline_date', '')::date,
        coalesce(nullif(v_task_payload->>'priority', ''), 'Medium'),
        coalesce(nullif(v_task_payload->>'status', ''), 'New'),
        'client_update',
        v_update.raw_input,
        false,
        null,
        case
          when lower(btrim(coalesce(v_task_payload->>'status', ''))) = 'done'
            then v_now
          else null
        end,
        null,
        v_now
      )
      returning id into v_task_id;

      v_event_new_value := jsonb_build_object(
        'task_id', v_task_id,
        'task_title', v_task_payload->>'task_title',
        'subtask_order', v_next_subtask_order
      );
    elsif v_item.type = 'update_subtask' then
      if v_mutation->>'kind' is distinct from 'update_subtask'
        or jsonb_typeof(v_mutation->'updates') <> 'object'
        or (v_mutation->>'taskId')::bigint is distinct from v_item.target_task_id then
        raise exception using
          errcode = 'P0001',
          message = 'INVALID_SUBTASK_UPDATE_PAYLOAD';
      end if;

      v_updates := v_mutation->'updates';

      if v_updates = '{}'::jsonb
        or (
          v_updates - array[
            'task_title',
            'amount',
            'amount_value',
            'currency_code',
            'deadline_text',
            'deadline_date',
            'priority',
            'status'
          ]
        ) <> '{}'::jsonb then
        raise exception using
          errcode = 'P0001',
          message = 'INVALID_SUBTASK_UPDATE_PAYLOAD';
      end if;

      update public.tasks as task
      set
        task_title = case when v_updates ? 'task_title'
          then v_updates->>'task_title' else task.task_title end,
        amount = case when v_updates ? 'amount'
          then v_updates->>'amount' else task.amount end,
        amount_value = case when v_updates ? 'amount_value'
          then nullif(v_updates->>'amount_value', '')::numeric else task.amount_value end,
        currency_code = case when v_updates ? 'currency_code'
          then v_updates->>'currency_code' else task.currency_code end,
        deadline_text = case when v_updates ? 'deadline_text'
          then v_updates->>'deadline_text' else task.deadline_text end,
        deadline_date = case when v_updates ? 'deadline_date'
          then nullif(v_updates->>'deadline_date', '')::date else task.deadline_date end,
        priority = case when v_updates ? 'priority'
          then v_updates->>'priority' else task.priority end,
        status = case when v_updates ? 'status'
          then v_updates->>'status' else task.status end,
        completed_at = case
          when v_updates ? 'status' then
            case
              when lower(btrim(coalesce(v_updates->>'status', ''))) = 'done'
                then v_now
              else null
            end
          else task.completed_at
        end,
        updated_at = v_now
      where task.id = v_item.target_task_id
        and task.project_id = v_project.id
        and task.user_id = v_user_id
        and task.deleted_at is null
      returning task.id into v_task_id;

      if not found then
        raise exception using
          errcode = 'P0001',
          message = 'SUBTASK_UPDATE_FAILED';
      end if;
    elsif v_item.type in (
      'deadline_change',
      'budget_change',
      'priority_change',
      'status_change'
    ) then
      if v_mutation->>'kind' is distinct from 'project_field'
        or jsonb_typeof(v_mutation->'updates') <> 'object' then
        raise exception using
          errcode = 'P0001',
          message = 'INVALID_PROJECT_UPDATE_PAYLOAD';
      end if;

      v_updates := v_mutation->'updates';

      if v_updates = '{}'::jsonb
        or (
          v_item.type = 'deadline_change'
          and (v_updates - array['deadline_text', 'deadline_date']) <> '{}'::jsonb
        )
        or (
          v_item.type = 'budget_change'
          and (v_updates - array['amount', 'amount_value', 'currency_code']) <> '{}'::jsonb
        )
        or (
          v_item.type = 'priority_change'
          and (
            (v_updates - array['priority']) <> '{}'::jsonb
            or coalesce(v_updates->>'priority', '') not in (
              'Low',
              'Medium',
              'High'
            )
          )
        )
        or (
          v_item.type = 'status_change'
          and (v_updates - array['status']) <> '{}'::jsonb
        ) then
        raise exception using
          errcode = 'P0001',
          message = 'INVALID_PROJECT_UPDATE_PAYLOAD';
      end if;

      update public.projects as project
      set
        deadline_text = case when v_updates ? 'deadline_text'
          then v_updates->>'deadline_text' else project.deadline_text end,
        deadline_date = case when v_updates ? 'deadline_date'
          then nullif(v_updates->>'deadline_date', '')::date else project.deadline_date end,
        amount = case when v_updates ? 'amount'
          then v_updates->>'amount' else project.amount end,
        amount_value = case when v_updates ? 'amount_value'
          then nullif(v_updates->>'amount_value', '')::numeric else project.amount_value end,
        currency_code = case when v_updates ? 'currency_code'
          then v_updates->>'currency_code' else project.currency_code end,
        priority = case when v_updates ? 'priority'
          then v_updates->>'priority' else project.priority end,
        status = case when v_updates ? 'status'
          then v_updates->>'status' else project.status end,
        updated_at = v_now
      where project.id = v_project.id
        and project.user_id = v_user_id
        and project.deleted_at is null;

      get diagnostics v_affected_count = row_count;

      if v_affected_count <> 1 then
        raise exception using
          errcode = 'P0001',
          message = 'PROJECT_UPDATE_FAILED';
      end if;

      if v_item.type = 'priority_change' then
        v_has_priority_change := true;
      end if;
    elsif v_item.type = 'client_detail_change' then
      v_project_client_updates := coalesce(v_mutation #> '{projectUpdates}', '{}'::jsonb);
      v_client_updates := coalesce(v_mutation #> '{clientUpdates}', '{}'::jsonb);
      v_task_client_updates := coalesce(v_mutation #> '{taskUpdates}', '{}'::jsonb);

      if v_mutation->>'kind' is distinct from 'client_detail'
        or jsonb_typeof(v_project_client_updates) <> 'object'
        or jsonb_typeof(v_client_updates) <> 'object'
        or jsonb_typeof(v_task_client_updates) <> 'object' then
        raise exception using
          errcode = 'P0001',
          message = 'INVALID_CLIENT_UPDATE_PAYLOAD';
      end if;

      if (
          v_project_client_updates - array['client_name', 'contact_name']
        ) <> '{}'::jsonb
        or (
          v_client_updates - array[
            'name',
            'contact_name',
            'phone',
            'email',
            'notes'
          ]
        ) <> '{}'::jsonb
        or (
          v_task_client_updates - array['client_name', 'contact_name']
        ) <> '{}'::jsonb then
        raise exception using
          errcode = 'P0001',
          message = 'INVALID_CLIENT_UPDATE_PAYLOAD';
      end if;

      if v_project_client_updates <> '{}'::jsonb then
        v_updates := v_project_client_updates;

        update public.projects as project
        set
          client_name = case when v_updates ? 'client_name'
            then v_updates->>'client_name' else project.client_name end,
          contact_name = case when v_updates ? 'contact_name'
            then v_updates->>'contact_name' else project.contact_name end,
          updated_at = v_now
        where project.id = v_project.id
          and project.user_id = v_user_id
          and project.deleted_at is null;

        get diagnostics v_affected_count = row_count;

        if v_affected_count <> 1 then
          raise exception using
            errcode = 'P0001',
            message = 'PROJECT_CLIENT_UPDATE_FAILED';
        end if;
      end if;

      if v_project.client_id is not null
        and v_client_updates <> '{}'::jsonb then
        v_updates := v_client_updates;

        update public.clients as client
        set
          name = case when v_updates ? 'name'
            then v_updates->>'name' else client.name end,
          contact_name = case when v_updates ? 'contact_name'
            then v_updates->>'contact_name' else client.contact_name end,
          phone = case when v_updates ? 'phone'
            then v_updates->>'phone' else client.phone end,
          email = case when v_updates ? 'email'
            then v_updates->>'email' else client.email end,
          notes = case when v_updates ? 'notes'
            then v_updates->>'notes' else client.notes end
        where client.id = v_project.client_id
          and client.user_id = v_user_id;

        get diagnostics v_affected_count = row_count;

        if v_affected_count <> 1 then
          raise exception using
            errcode = 'P0001',
            message = 'CLIENT_UPDATE_FAILED';
        end if;
      end if;

      if v_task_client_updates <> '{}'::jsonb then
        v_updates := v_task_client_updates;

        select count(*)::integer
        into v_expected_count
        from public.tasks as task
        where task.project_id = v_project.id
          and task.user_id = v_user_id
          and task.deleted_at is null;

        update public.tasks as task
        set
          client_name = case when v_updates ? 'client_name'
            then v_updates->>'client_name' else task.client_name end,
          contact_name = case when v_updates ? 'contact_name'
            then v_updates->>'contact_name' else task.contact_name end,
          updated_at = v_now
        where task.project_id = v_project.id
          and task.user_id = v_user_id
          and task.deleted_at is null;

        get diagnostics v_affected_count = row_count;

        if v_affected_count <> v_expected_count then
          raise exception using
            errcode = 'P0001',
            message = 'TASK_CLIENT_SYNC_FAILED';
        end if;
      end if;
    elsif v_item.type in (
      'project_note',
      'client_note',
      'duplicate_warning',
      'no_action'
    ) then
      if v_mutation->>'kind' is distinct from 'timeline_only' then
        raise exception using
          errcode = 'P0001',
          message = 'INVALID_TIMELINE_ONLY_PAYLOAD';
      end if;
    else
      raise exception using
        errcode = 'P0001',
        message = 'UNSUPPORTED_UPDATE_ITEM';
    end if;

    insert into public.project_timeline_events (
      user_id,
      project_id,
      event_type,
      event_title,
      event_summary,
      source_update_id,
      source_item_id,
      target_task_id,
      target_field,
      old_value,
      new_value,
      actor_user_id,
      metadata,
      created_at
    )
    values (
      v_user_id,
      v_project.id,
      v_event_payload->>'eventType',
      v_event_payload->>'title',
      nullif(v_event_payload->>'summary', ''),
      v_update.id,
      v_item.id,
      case
        when v_item.type in ('new_subtask', 'update_subtask') then v_task_id
        when v_item.type in (
          'project_note',
          'client_note',
          'duplicate_warning',
          'no_action'
        ) then v_item.target_task_id
        else null
      end,
      nullif(v_event_payload->>'targetField', ''),
      v_item.old_value,
      v_event_new_value,
      v_user_id,
      case
        when v_event_payload ? 'metadata'
          and jsonb_typeof(v_event_payload->'metadata') = 'object'
        then v_event_payload->'metadata'
        else null
      end,
      v_now
    )
    returning * into v_event;

    v_created_timeline_events :=
      v_created_timeline_events || jsonb_build_array(to_jsonb(v_event));
  end loop;

  if cardinality(v_accepted_ids) > 0 then
    update public.project_update_items as item
    set
      status = 'applied',
      accepted_at = v_now,
      applied_at = v_now,
      accepted_by = v_user_id,
      applied_by = v_user_id
    where item.id = any(v_accepted_ids)
      and item.project_update_id = v_update.id
      and item.project_id = v_project.id
      and item.user_id = v_user_id
      and item.status in ('suggested', 'accepted', 'rejected');

    get diagnostics v_affected_count = row_count;

    if v_affected_count <> cardinality(v_accepted_ids) then
      raise exception using
        errcode = 'P0001',
        message = 'MARK_APPLIED_ITEMS_FAILED';
    end if;
  end if;

  if cardinality(v_rejected_ids) > 0 then
    update public.project_update_items as item
    set
      status = 'rejected',
      rejected_at = v_now,
      rejected_by = v_user_id
    where item.id = any(v_rejected_ids)
      and item.project_update_id = v_update.id
      and item.project_id = v_project.id
      and item.user_id = v_user_id
      and item.status in ('suggested', 'accepted', 'rejected');

    get diagnostics v_affected_count = row_count;

    if v_affected_count <> cardinality(v_rejected_ids) then
      raise exception using
        errcode = 'P0001',
        message = 'MARK_REJECTED_ITEMS_FAILED';
    end if;
  end if;

  if v_update.source_share_message_id is not null then
    perform set_config(
      'text2task.client_share_apply_update_id',
      p_update_id::text,
      true
    );
  end if;

  update public.project_updates as update_row
  set
    status = 'applied',
    reviewed_by = v_user_id,
    applied_by = v_user_id,
    reviewed_at = v_now,
    applied_at = v_now,
    apply_failed_at = null,
    apply_error_code = null
  where update_row.id = v_update.id
    and update_row.user_id = v_user_id
    and update_row.status = 'applying'
    and update_row.apply_attempt_id = p_apply_attempt_id
  returning update_row.* into v_final_update;

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'MARK_UPDATE_APPLIED_FAILED';
  end if;

  if v_has_priority_change then
    update public.projects as project
    set
      priority_source = 'user',
      updated_at = v_now
    where project.id = v_project.id
      and project.user_id = v_user_id
      and project.deleted_at is null;

    get diagnostics v_affected_count = row_count;

    if v_affected_count <> 1 then
      raise exception using
        errcode = 'P0001',
        message = 'PROJECT_PRIORITY_PROVENANCE_UPDATE_FAILED';
    end if;
  end if;

  -- Reconcile project completion in the same transaction as every task
  -- mutation above: a Project Update that finishes the last remaining
  -- active subtask (via new_subtask or update_subtask items) now completes
  -- the parent project exactly like the direct-edit and bulk-status paths.
  if cardinality(v_accepted_ids) > 0 then
    perform public.reconcile_project_completion(v_project.id, v_user_id, v_now);
  end if;

  if cardinality(v_accepted_ids) > 0 then
    select coalesce(
      jsonb_agg(to_jsonb(item) order by item.created_at, item.id),
      '[]'::jsonb
    )
    into v_applied_items
    from public.project_update_items as item
    where item.id = any(v_accepted_ids)
      and item.project_update_id = v_update.id
      and item.user_id = v_user_id;
  end if;

  if cardinality(v_rejected_ids) > 0 then
    select coalesce(
      jsonb_agg(to_jsonb(item) order by item.created_at, item.id),
      '[]'::jsonb
    )
    into v_rejected_items
    from public.project_update_items as item
    where item.id = any(v_rejected_ids)
      and item.project_update_id = v_update.id
      and item.user_id = v_user_id;
  end if;

  if v_update.source_share_message_id is not null then
    perform public.finalize_share_message_conversion(
      v_update.source_share_message_id,
      p_update_id
    );
  end if;

  return jsonb_build_object(
    'update', to_jsonb(v_final_update),
    'appliedItems', v_applied_items,
    'rejectedItems', v_rejected_items,
    'timelineEvents', v_created_timeline_events
  );
end;
$$;


comment on function public.apply_project_update_transaction(
  uuid,
  uuid,
  uuid[],
  uuid[],
  jsonb,
  jsonb
) is
  'Atomically applies one claimed Project Update review, commits item, mutation, timeline, and lifecycle writes, records user priority provenance for accepted project-level priority changes, and reconciles project completion via the shared reconcile_project_completion check. Phase 6C: for client_share rows only (source_share_message_id is not null), also establishes the transaction-local row-bound capability immediately before the applied-status write, and calls finalize_share_message_conversion immediately before the final return -- both a complete no-op for every other source type.';

-- =========================================================
-- 3. public.set_share_message_status (CREATE OR REPLACE -- same
--    signature/security/grants, preserved from 202608190001 except for
--    the terminal-guard insertion proven above)
-- =========================================================

create or replace function public.set_share_message_status(
  p_message_id uuid,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_message_user_id uuid;
  v_message_project_id uuid;
  v_project_deleted_at timestamptz;
  v_existing_reviewed_at timestamptz;
  v_existing_status text;
  v_reviewed_at timestamptz;
  v_resolved_at timestamptz;
  v_now timestamptz := now();
begin
  if v_user_id is null then
    raise exception using errcode = 'P0001', message = 'UNAUTHORIZED';
  end if;

  -- Phase 5 target statuses only. 'converted' is deliberately absent --
  -- Phase 6 owns that transition, through its own future code, not this
  -- function.
  if p_status is null or p_status not in ('new', 'reviewed', 'resolved', 'dismissed') then
    raise exception using errcode = 'P0001', message = 'SHARE_MESSAGE_STATUS_INVALID';
  end if;

  if p_message_id is null then
    raise exception using errcode = 'P0001', message = 'SHARE_MESSAGE_NOT_FOUND';
  end if;

  select message.user_id, message.project_id, message.reviewed_at, message.status
    into v_message_user_id, v_message_project_id, v_existing_reviewed_at, v_existing_status
    from public.share_messages as message
    where message.id = p_message_id and message.user_id = v_user_id
    for update;

  if v_message_user_id is null then
    raise exception using errcode = 'P0001', message = 'SHARE_MESSAGE_NOT_FOUND';
  end if;

  select project.deleted_at
    into v_project_deleted_at
    from public.projects as project
    where project.id = v_message_project_id;

  if v_project_deleted_at is not null then
    raise exception using errcode = 'P0001', message = 'SHARE_MESSAGE_NOT_FOUND';
  end if;

  if v_existing_status = 'converted' then
    raise exception using errcode = 'P0001', message = 'SHARE_MESSAGE_STATUS_TERMINAL';
  end if;

  if p_status = 'new' then
    v_reviewed_at := null;
    v_resolved_at := null;
  elsif p_status = 'reviewed' then
    v_reviewed_at := v_now;
    v_resolved_at := null;
  elsif p_status = 'resolved' then
    v_reviewed_at := coalesce(v_existing_reviewed_at, v_now);
    v_resolved_at := v_now;
  else
    -- dismissed
    v_reviewed_at := v_now;
    v_resolved_at := null;
  end if;

  -- Only the review/visibility lifecycle columns are ever touched here
  -- (status, reviewed_at, resolved_at) -- body, author_type,
  -- author_display_name, parent_id, share_link_id, project_id, user_id
  -- and created_at are never referenced on the left-hand side of this
  -- UPDATE at all, matching enforce_share_message_integrity's own
  -- UPDATE-immutability check exactly (that trigger independently
  -- re-verifies this too).
  update public.share_messages
    set
      status = p_status,
      reviewed_at = v_reviewed_at,
      resolved_at = v_resolved_at
    where id = p_message_id and user_id = v_user_id;

  return jsonb_build_object(
    'messageId', p_message_id,
    'status', p_status,
    'reviewedAt', v_reviewed_at,
    'resolvedAt', v_resolved_at
  );
end;
$$;


comment on function public.set_share_message_status(uuid, text) is
  'Owner-only workflow-state transition (new/reviewed/resolved/dismissed only -- converted is exclusively Phase 6C''s, never accepted as a target here) for one owned message. SECURITY DEFINER; obtains and null-checks auth.uid() internally; owner-scoped; project soft-delete checked; row locked FOR UPDATE. Phase 6C: loads the row''s current status in that same locked read and rejects with SHARE_MESSAGE_STATUS_TERMINAL, before any mutation is computed, if it is already ''converted'' -- the sole existing path capable of moving share_messages.status at all, so this one guard makes converted a true terminal state. Updates only status/reviewed_at/resolved_at -- never body, author_type, author_display_name, parent_id, share_link_id, project_id, user_id or created_at. Writes to no other table.';

-- =========================================================
-- 4. public.enforce_project_update_client_share_apply_boundary
--    (CREATE OR REPLACE FUNCTION ONLY -- the trigger
--    project_updates_enforce_client_share_apply_boundary is NEVER
--    dropped and is not redeclared; preserved from 202608230001 except
--    for the predicate narrowing proven above)
-- =========================================================

create or replace function public.enforce_project_update_client_share_apply_boundary()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if new.source_type = 'client_share'
    and new.status = 'applied' then

    if tg_op = 'INSERT' then
      if current_setting('text2task.client_share_apply_update_id', true)
          is distinct from new.id::text then
        raise exception using
          errcode = 'P0001',
          message = 'PROJECT_UPDATE_SOURCE_NOT_APPLIABLE';
      end if;
    elsif tg_op = 'UPDATE'
        and old.status is distinct from 'applied' then
      if current_setting('text2task.client_share_apply_update_id', true)
          is distinct from new.id::text then
        raise exception using
          errcode = 'P0001',
          message = 'PROJECT_UPDATE_SOURCE_NOT_APPLIABLE';
      end if;
    end if;

  end if;

  return new;
end;
$$;


comment on function public.enforce_project_update_client_share_apply_boundary() is
  'Phase 6C client_share apply boundary (narrowed in place from the Phase 6B version -- never dropped): "applying" is no longer blocked for client_share (the real apply_project_update_transaction always independently re-validates and performs real work regardless of how "applying" was reached -- proven safe by the Phase 6C security audit). An *entering* transition into "applied" for client_share -- a direct INSERT already at "applied", or an UPDATE from any prior status other than "applied" -- is permitted only when the transaction-local capability text2task.client_share_apply_update_id matches the exact row id, a value only apply_project_update_transaction itself ever sets, immediately before its own authoritative applied-status write. An already-applied client_share row receiving an ordinary non-status update (OLD.status=''applied'' AND NEW.status=''applied'') does not require the capability -- this guard protects establishing applied, not every future write to an already-applied row. TG_OP-safe: OLD is referenced only inside a branch that has already established TG_OP=''UPDATE''.';
